item {
  id: 1
  name: 'person'
}

item {
  id: 2
  name: 'traffic light'
}

item {
  id: 3
  name: 'bus'
}

item {
  id: 4
  name: 'car'
}

item {
  id: 5
  name: 'motorbike'
}

item {
  id: 6
  name: 'traffic sign'
}



